### ISSUE TITLE
@six.python_2_unicode_compatible causing scraper stack traces in staging

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/scraper#188]
```
WARNING: yacc table file version is out of date
Traceback (most recent call last):
  File "/run_scraper.py", line 36, in <module>
    import scraper
  File "/scraper.py", line 42, in <module>
    import google.cloud.datastore as cloud_datastore
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/datastore/__init__.py", line 61, in <module>
    from google.cloud.datastore.client import Client
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/datastore/client.py", line 28, in <module>
    from google.cloud.datastore._http import HTTPDatastoreAPI
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/datastore/_http.py", line 19, in <module>
    from google.cloud import _http as connection_module
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 23, in <module>
    from google.cloud import exceptions
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/exceptions.py", line 24, in <module>
    from google.api.core import exceptions
  File "/usr/local/lib/python2.7/dist-packages/google/api/core/exceptions.py", line 43, in <module>
    @six.python_2_unicode_compatible
AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'
```

**Comment by pboothe** [comment]
Fixed in https://github.com/m-lab/scraper/pull/146
