### ISSUE TITLE
Scraper got wedged

### ISSUE THREAD

**Issue by pboothe** [m-lab/scraper#66]
I don't know why the instance was not restarted after crashing.

`kubectl logs` on the wedged instance got:
```
[2017-06-15 08:04:24,584 INFO discovery.py:863 rsync://ndt.iupui.mlab1.bkk01.measurement-lab.org:7999/ndt] URL being requested: POST https://www.googleapis.com/upload/storage/v1/b/scraper-mlab-oti/o?uploadType=resumable&alt=json&name=ndt%2F2017%2F06%2F14%2F20170614T000000Z-mlab1-bkk01-ndt-0011.tgz
Traceback (most recent call last):
  File "/run_scraper.py", line 207, in <module>
    main(sys.argv)
  File "/run_scraper.py", line 186, in main
    storage_service)
  File "/scraper.py", line 887, in upload_if_allowed
    max_new_archived_date())
  File "/scraper.py", line 924, in upload_up_to_date
    args.rsync_module, args.bucket)
  File "<decorator-gen-3>", line 2, in upload_tarfile
  File "/usr/local/lib/python2.7/dist-packages/prometheus_client/core.py", line 879, in wrapped
    return func(*args, **kwargs)
  File "<decorator-gen-2>", line 2, in upload_tarfile
  File "/usr/local/lib/python2.7/dist-packages/retry/api.py", line 74, in retry_decorator
    logger)
  File "/usr/local/lib/python2.7/dist-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/scraper.py", line 617, in upload_tarfile
    progress, response = request.next_chunk()
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/http.py", line 972, in next_chunk
    headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 175, in new_request
    redirections, connection_type)
  File "/usr/local/lib/python2.7/dist-packages/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1659, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1399, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/local/lib/python2.7/dist-packages/httplib2/__init__.py", line 1355, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 714, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 608, in read
    v = self._sslobj.read(len or 1024)
ssl.SSLError: ('The read operation timed out',)
```

**Comment by pboothe** [comment]
`kubectl -n scraper delete po/bkk01-mlab1-ndt-iupui-ndt-660533955-vn15g` fixed the situation (deleting the Pod causes the ReplicaSet to create a new one, and presumably the new one won't get wedged due to a transient network/service condition), but I still have questions about why things were not restarted automatically by Kubernetes.
